Repository 42-world/42world-Backend, pull requests merged in 2022-06, with the labels that each got.

#251 Fix: 42인증하지 않은 유저도 로그아웃 가능하도록 변경
  apps/api/src/auth/auth.controller.ts
Labels: Hot Fix

#252 Feat: 내정보 가져오기 api, novice도 가능하도록 수정
  apps/api/src/user/user.controller.ts
Labels: enhancement

#253 Fix: makefile, clean-all db 파일 삭제, 경로 수정
  Makefile
Labels: bug

#255 Fix: http error
  apps/api/src/article/article.service.ts
  apps/api/src/category/category.service.ts
  apps/api/src/comment/comment.controller.ts
  apps/api/src/comment/comment.service.ts
  apps/api/test/e2e/article.e2e-spec.ts
  apps/api/test/e2e/comment.e2e-spec.ts
Labels: bug

#249 Refactor: find-all-article dto를 article dto로 통합
  apps/api/src/article/article.controller.ts
  apps/api/src/article/article.service.ts
  apps/api/src/article/dto/response/find-all-article-response.dto.ts
  apps/api/src/article/repositories/article.repository.ts
Labels: API CHANGED!

#254 Fix: prettier 설정이 적용이 안되던 문제 수정
  .eslintrc.js
  .prettierrc
Labels: bug

#266 Feat: user profile api에 intraId 추가
  apps/api/src/user/dto/response/base-user-response.dto.ts
  apps/api/src/user/dto/response/user-profile-response.dto.ts
  apps/api/src/user/dto/user-profile.mapper.ts
  apps/api/src/user/user.controller.ts
  apps/api/test/e2e/user.e2e-spec.ts
  libs/entity/src/user/user.entity.ts
Labels: enhancement

#264 Feat: admin, batch dockerfile 추가
  Makefile
  apps/api/src/main.ts
  infra/admin.Dockerfile
  infra/batch.Dockerfile
  infra/docker-compose.yml
  infra/docker-stack-alpha.yml
  infra/docker-stack-prod.yml
Labels: ENV CHANGED!
