Repository 42-world/42world-Backend, pull requests merged in 2022-07, with the labels that each got.

#211 Refactor: dummy 반영
  apps/api/src/user/user.controller.ts
  apps/api/test/e2e/article.e2e-spec.ts
  apps/api/test/e2e/best.e2e-spec.ts
  apps/api/test/e2e/category.e2e-spec.ts
  apps/api/test/e2e/comment.e2e-spec.ts
  apps/api/test/e2e/e2e-test.base.module.ts
  apps/api/test/e2e/image.e2e-spec.ts
  apps/api/test/e2e/intra-auth.e2e-spec.ts
  apps/api/test/e2e/notification.e2e-spec.ts
  apps/api/test/e2e/reaction.e2e-spec.ts
  apps/api/test/e2e/user.e2e-spec.ts
  apps/api/test/e2e/utils/dummy.ts
Labels: Legacy

#272 Refactor: article search
  apps/api/src/article/article.controller.ts
  apps/api/src/article/article.service.ts
  apps/api/src/article/dto/request/search-article-request.dto.ts
  apps/api/src/article/repositories/article.repository.ts
  apps/api/test/e2e/article.e2e-spec.ts
Labels: Hot Fix, API CHANGED!

#273 Feat: email stibee
  apps/api/src/app.module.ts
  apps/api/src/intra-auth/intra-auth.config.ts
  apps/api/src/intra-auth/intra-auth.constant.ts
  apps/api/src/intra-auth/intra-auth.module.ts
  apps/api/src/intra-auth/intra-auth.service.ts
  apps/api/src/intra-auth/intra-auth.utils.ts
  apps/api/src/intra-auth/mail.service.ts
  apps/api/src/intra-auth/stibee.service.ts
  apps/api/src/intra-auth/unsubscribe-stibee.service.ts
  apps/api/src/user/user.controller.ts
  apps/api/test/e2e/e2e-test.base.module.ts
  apps/api/test/e2e/intra-auth.e2e-spec.ts
  package.json
  yarn.lock
Labels: Hot Fix, ENV CHANGED!

#281 Fix: cookie 옵션, alpha, prod일때 다르게 설정 및 옵션 추가
  apps/api/src/auth/auth.controller.ts
  libs/utils/src/utils.ts
Labels: bug, Next Upgrade

#276 Feat: slack 알람 alpha도 받도록 변경
  libs/utils/src/utils.ts
Labels: ENV CHANGED!

#274 Fix: makefile docker compose
  Makefile
  infra/docker-compose.yml
Labels: bug

#286 CORS origin 으로 regex 를 쓸수있도록 변경
  apps/api/src/main.ts
Labels: ENV CHANGED!

#288 fix: profile api 제거
  apps/api/src/user/user.controller.ts
Labels: API CHANGED!

#290 Fix: my comments, my reaction article
  apps/api/src/comment/repositories/comment.repository.ts
  apps/api/src/reaction/repositories/reaction-article.repository.ts
  apps/api/test/e2e/user.e2e-spec.ts
Labels: bug, Hot Fix

#295 Fix: unit test
  Makefile
  libs/utils/src/utils.spec.ts
Labels: bug
