Repository 42-world/42world-Backend, pull requests merged in 2022-03, with the labels that each got.

#104 Feat: pagination me
  src/article/article.service.ts
  src/article/repositories/article.repository.ts
  src/comment/comment.service.ts
  src/comment/repositories/comment.repository.ts
  src/reaction/reaction.service.ts
  src/reaction/repositories/reaction-article.repository.ts
  src/user/user.controller.ts
  test/e2e/user.e2e-spec.ts
  test/e2e/utils/dummy.ts
Labels: Next Upgrade

#125 Feat: nickname to intraid
  README.md
  config/sample.env.dev
  src/app.module.ts
  src/auth/constant.ts
  src/auth/github.strategy.ts
  src/auth/interfaces/github-profile.interface.ts
  src/auth/jwt-auth.guard.ts
  src/cache/cache.module.ts
  src/cache/cache.service.ts
  src/cache/dto/intra-auth.dto.ts
  src/database/migrations/1645622620898-intra-auth.ts
  src/ft-auth/ft-auth.controller.spec.ts
  src/ft-auth/ft-auth.module.ts
  src/ft-auth/ft-auth.service.ts
  src/ft-auth/interfaces/ft-auth.interface.ts
  src/intra-auth/constant.ts
  src/intra-auth/dto/signin-intra-auth.dto.ts
  src/intra-auth/entities/intra-auth.entity.ts
  src/intra-auth/intra-auth.controller.spec.ts
  src/intra-auth/intra-auth.controller.ts
  src/intra-auth/intra-auth.module.ts
  src/intra-auth/intra-auth.service.spec.ts
  src/intra-auth/intra-auth.service.ts
  src/intra-auth/intra-auth.utils.ts
  src/main.ts
  src/user/dto/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.service.ts
  test/e2e/image.e2e-spec.ts
  test/e2e/intra-auth.e2e-spec.ts
  test/e2e/jest-e2e.json
  test/e2e/reaction.e2e-spec.ts
  test/e2e/user.e2e-spec.ts
  test/e2e/utils/dummy.ts
  tsconfig.json
  views/intra-auth/results.ejs
  views/intra-auth/signin.ejs
Labels: enhancement

#139 Feat: github action을 통한 test workflow 추가
  .github/workflows/test.yml
Labels: enhancement

#135 Fix: ft-checkin 서초 필드 오타때문에 값이 0으로 나오는 문제 수정
  src/ft-checkin/ft-checkin.service.ts
Labels: bug
