Repository 42-world/42world-Backend, pull requests merged in 2022-02, with the labels that each got.

#80 readme에 env 파일 샘플 추가, 테스트 내용 추가
  Makefile
  README.md
  config/sample.env.dev
Labels: documentation

#81 typeorm log, dev 환경일때만 되도록 수정
  src/database/ormconfig.ts
Labels: bug

#91 500 error 글로벌 필터 적용, 에러 발생시 슬랙으로 메시지 발송
  src/app.controller.ts
  src/auth/auth.controller.ts
  src/filters/all-exception.filter.ts
  src/filters/constant.ts
  src/filters/internal-server-error-exception.filter.ts
  src/filters/typeorm-exception.filter.ts
  src/main.ts
  src/utils.ts
Labels: Next Upgrade

#93 [FIX] 작성자가 글에 접속하면 조회수가 오르지 않도록 수정
  src/article/article.controller.ts
Labels: enhancement

#82 env 개편
  Dockerfile
  Makefile
  README.md
  docker-compose.yml
  docker-compose_backup.yml
  package.json
  src/app.module.ts
  src/database/seeder/seeder.module.ts
  src/utils.ts
  test/test.base.module.ts
Labels: Next Upgrade

#96 timezone, kst에 맞게 변경
  src/database/ormconfig.ts
Labels: bug, Next Upgrade

#105 Fix: access_token_naming
  src/auth/auth.controller.ts
  src/auth/constants/access-token.ts
  src/auth/jwt.strategy.ts
  src/main.ts
  test/e2e/image.e2e-spec.ts
  test/e2e/reaction.e2e-spec.ts
  test/e2e/user.e2e-spec.ts
Labels: Next Upgrade
