Repository 42-world/42world-Backend, pull requests merged in 2022-04, with the labels that each got.

#173 Chore: bump nestjs/cli from 8.2.0 to 8.2.5
  yarn.lock
Labels: dependencies

#191 Docs: add codacy badge
  README.md
Labels: documentation

#203 Docs: 테스트 실행하기 형식 변경
  README.md
Labels: documentation

#178 Docs: 기여한 사람 추가
  README.md
Labels: documentation

#199 Chore: ignore README.md in testCI
  .github/workflows/test.yml
Labels: documentation, enhancement

#207 Docs: dev-tool version 명시
  .github/workflows/codeql-analysis.yml
  .github/workflows/test.yml
  README.md
Labels: documentation

#213 Chore: bump ejs from 3.1.6 to 3.1.7
  yarn.lock
Labels: dependencies

#205 Refactor: test base module
  Makefile
  apps/api/test/e2e/article.e2e-spec.ts
  apps/api/test/e2e/category.e2e-spec.ts
  apps/api/test/e2e/comment.e2e-spec.ts
  apps/api/test/e2e/e2e-test.base.module.ts
  apps/api/test/e2e/image.e2e-spec.ts
  apps/api/test/e2e/intra-auth.e2e-spec.ts
  apps/api/test/e2e/notification.e2e-spec.ts
  apps/api/test/e2e/reaction.e2e-spec.ts
  apps/api/test/e2e/user.e2e-spec.ts
Labels: enhancement

#201 Feature: best article
  apps/api/src/article/repositories/article.repository.ts
  apps/api/test/e2e/article.e2e-spec.ts
  apps/api/test/e2e/best.e2e-spec.ts
  apps/api/test/e2e/category.e2e-spec.ts
  apps/api/test/e2e/comment.e2e-spec.ts
  apps/api/test/e2e/image.e2e-spec.ts
  apps/api/test/e2e/intra-auth.e2e-spec.ts
  apps/api/test/e2e/notification.e2e-spec.ts
  apps/api/test/e2e/reaction.e2e-spec.ts
  apps/api/test/e2e/user.e2e-spec.ts
  apps/api/test/e2e/utils/dummy.ts
Labels: Next Upgrade

#140 Feat: adminjs
  .adminjs/.entry.js
  apps/admin/src/admin.module.ts
  apps/admin/src/adminJs/admin-js.module.ts
  apps/admin/src/main.ts
  apps/admin/tsconfig.app.json
  apps/api/src/article/article.service.ts
  apps/api/src/user/user.service.ts
  libs/entity/src/article/article.entity.ts
  libs/entity/src/best/best.entity.ts
  libs/entity/src/category/category.entity.ts
  libs/entity/src/comment/comment.entity.ts
  libs/entity/src/intra-auth/intra-auth.entity.ts
  libs/entity/src/notification/notification.entity.ts
  libs/entity/src/reaction/reaction-article.entity.ts
  libs/entity/src/reaction/reaction-comment.entity.ts
  libs/entity/src/user/user.entity.ts
  nest-cli.json
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#198 Feature: ft-checkin 을 위한 Batch 어플리케이션 추가됨
  Makefile
  apps/api/src/app.module.ts
  apps/api/src/ft-checkin/ft-checkin.controller.ts
  apps/api/src/ft-checkin/ft-checkin.service.ts
  apps/batch/src/batch.controller.ts
  apps/batch/src/batch.module.ts
  apps/batch/src/ft-checkin/ft-checkin.constant.ts
  apps/batch/src/ft-checkin/ft-checkin.module.ts
  apps/batch/src/ft-checkin/ft-checkin.service.ts
  apps/batch/src/main.ts
  apps/batch/test/app.e2e-spec.ts
  apps/batch/test/jest-e2e.json
  apps/batch/tsconfig.app.json
  apps/scheduler/src/main.ts
  apps/scheduler/src/scheduler.controller.spec.ts
  apps/scheduler/src/scheduler.controller.ts
  apps/scheduler/src/scheduler.module.ts
  apps/scheduler/src/scheduler.service.ts
  apps/scheduler/tsconfig.app.json
  docker-compose.yml
  docker-stack-alpha.yml
  docker-stack-prod.yml
  libs/common/src/cache/cache.module.ts
  libs/common/src/cache/dto/ft-checkin.constant.ts
  libs/common/src/cache/dto/ft-checkin.dto.ts
  nest-cli.json
  package.json
  yarn.lock
Labels: enhancement
