Repository 42-world/42world-Backend, pull requests merged in 2022-01, with the labels that each got.

#18 Feature/GitHub login
  package.json
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/constant.ts
  src/auth/constants/access-token.ts
  src/auth/github-auth.guard.ts
  src/auth/github.strategy.ts
  src/auth/interfaces/github-profile.interface.ts
  src/auth/interfaces/jwt-payload.interface.ts
  src/auth/jwt-auth.guard.ts
  src/auth/jwt.strategy.ts
  src/main.ts
  src/user/entities/user.entity.ts
  src/user/repositories/user.repository.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  src/utils.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#28 Feature/42 auth
  nest-cli.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/authenticate/authenticate.controller.spec.ts
  src/authenticate/authenticate.controller.ts
  src/authenticate/authenticate.module.ts
  src/authenticate/authenticate.service.ts
  src/authenticate/dto/update-authenticate.dto.ts
  src/config/mail.config.ts
  src/ft-auth/dto/create-ft-auth.dto.ts
  src/ft-auth/dto/update-authenticate.dto.ts
  src/ft-auth/entities/ft-auth.entity.ts
  src/ft-auth/ft-auth.controller.spec.ts
  src/ft-auth/ft-auth.controller.ts
  src/ft-auth/ft-auth.module.ts
  src/ft-auth/ft-auth.service.spec.ts
  src/ft-auth/ft-auth.service.ts
  src/ft-auth/ft-auth.utils.ts
  src/ft-auth/interfaces/ft-auth.interface.ts
  src/ft-auth/templates/signin.ejs
  src/main.ts
  src/user/dto/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#30 Fix: 게시글 검색시, query string validate 오류 수정
  src/article/dto/find-all-article.dto.ts
Labels: bug

#32 Feat: soft delete 추가
  src/article/article.service.ts
  src/article/entities/article.entity.ts
  src/article/repositories/article.repository.ts
  src/category/category.service.ts
  src/category/entities/category.entity.ts
  src/comment/comment.service.ts
  src/comment/entities/comment.entity.ts
  src/user/entities/user.entity.ts
  src/user/repositories/user.repository.ts
  src/user/user.service.ts
Labels: enhancement

#31 게시글 조회수, 댓글수 기능 추가
  src/article/article.controller.ts
  src/article/article.module.ts
  src/article/article.service.ts
  src/article/entities/article.entity.ts
  src/article/repositories/article.repository.ts
  src/category/category.module.ts
  src/category/category.service.ts
  src/category/repositories/category.repository.ts
  src/comment/comment.service.ts
Labels: enhancement

#38 Fix: encrypt way
  src/ft-auth/ft-auth.service.ts
  src/ft-auth/ft-auth.utils.ts
Labels: bug

#29 Feat: log 모듈, morgan, winston추가
  package.json
  src/app.module.ts
  src/main.ts
  yarn.lock
Labels: enhancement

#51 Fix: 게시글 리스트 순서 정렬 및 클러스터 입장 최대 인원 추가
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/article/article.controller.ts
  src/article/repositories/article.repository.ts
  src/ft-auth/ft-auth.service.ts
  src/ft-auth/ft-auth.utils.ts
  src/utils.ts
Labels: enhancement

#40 Docs: Readme 추가
  README.md
Labels: documentation

#50 Fix/지워진 게시글의 댓글에 접근가능한 오류 수정
  src/article/article.service.ts
  src/article/repositories/article.repository.ts
  src/category/repositories/category.repository.ts
  src/comment/comment.service.ts
  src/comment/repositories/comment.repository.ts
  src/user/repositories/user.repository.ts
Labels: bug

#49 Feature/mail fix
  Dockerfile
  src/ft-auth/ft-auth.controller.ts
  src/main.ts
  src/reaction/reaction.service.ts
  views/ft-auth/results.ejs
  views/ft-auth/signin.ejs
Labels: bug

#64 Refactor: 42 checkin service move from apps
  src/app.controller.ts
  src/app.module.ts
  src/ft-checkin/ft-checkin.controller.spec.ts
  src/ft-checkin/ft-checkin.controller.ts
  src/ft-checkin/ft-checkin.module.ts
  src/ft-checkin/ft-checkin.service.spec.ts
  src/ft-checkin/ft-checkin.service.ts
Labels: enhancement, invalid

#67 Feature/profile for novice
  src/auth/auth.decorator.ts
  src/auth/constants/metadata-keys.ts
  src/auth/jwt-auth.guard.ts
  src/ft-auth/ft-auth.controller.ts
  src/user/user.controller.ts
Labels: bug, enhancement, invalid

#70 Feature/pagination
  src/article/article.controller.ts
  src/article/article.service.ts
  src/article/dto/find-all-article.dto.ts
  src/article/helper/article.helper.ts
  src/article/repositories/article.repository.ts
  src/comment/comment.service.ts
  src/comment/repositories/comment.repository.ts
  src/pagination/page-meta.dto.ts
  src/pagination/page-options.dto.ts
  src/pagination/pagination.decorator.ts
  src/pagination/pagination.dto.ts
  src/pagination/pagination.enum.ts
  src/pagination/pagination.interface.ts
Labels: enhancement

#71 Fix/like article
  src/article/article.service.ts
  src/comment/comment.service.ts
  src/reaction/dto/like-article.dto.ts
  src/reaction/reaction.controller.ts
  src/reaction/reaction.service.ts
Labels: Hot Fix

#76 Fix: typeorm 에 timezone 설정
  src/database/ormconfig.ts
Labels: bug

#74 Fix: 댓글 생성 결과 dto 수정
  src/comment/comment.controller.ts
  src/comment/dto/create-comment-result.dto.ts
Labels: bug

#77 FIx: env 파일 이름 형식 변경
  .gitignore
  Makefile
  docker-compose.yml
  docker-compose_backup.yml
  src/utils.ts
Labels: bug, Hot Fix
